### ISSUE TITLE
Calling http://localhost:35729/livereload.js in production

### ISSUE THREAD

**Issue by seratch** [tsukaby/c-antenna#1]

**Comment by seratch** [comment]
<img width="1318" alt="screen shot 2015-09-03 at 11 42 51 pm" src="https://cloud.githubusercontent.com/assets/19658/9661411/89008c98-5295-11e5-894a-b688dcc11102.png">

**Comment by tsukaby** [comment]
@seratch Thank you! I will fix it next week!
